services:
  user-service:
    container_name: user-service
    build: .
    ports:
      - ${EXPOSE_PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_USER}:${DB_PASSWORD}@tcp(postgres:${DB_PORT})/${DB_NAME}
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
      - WAIT_BEFORE_HOSTS=15
      - WAIT_SLEEP_INTERVAL=3
    networks:
      - user-service-network

  postgres:
    image: postgres:14
    container_name: postgres_db
    ports:
      - ${EXPOSE_DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - user-service-network

volumes:
  database_postgres:

networks:
  user-service-network:
    driver: bridge