services:
  api:
    container_name: game-platform-ai-generator
    build: .
    ports:
      - ${EXPOSE_PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_CONNECTION=postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?sslmode=disable
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
      - WAIT_BEFORE_HOSTS=15
      - WAIT_SLEEP_INTERVAL=3
    networks:
      - game-platform-ai-generator-network

  postgres:
    image: postgres:14
    container_name: postgres_db
    ports:
      - ${EXPOSE_DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - game-platform-ai-generator-network

volumes:
  database_postgres:

networks:
  game-platform-ai-generator-network:
    driver: bridge